version: "3"

services:
  database:
    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: unless-stopped
    volumes:
      - ./sqlserver/data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=MyStrong@Pass123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - docker-network

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/.data/db:/root/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: unless-stopped
    ports:
      - 8001:${REDIS_INSIGHT_PORT}
    volumes:
      - ./redis_insight/.data/db:/db

  # Settings and configurations that are common for all containers
  minio:
    image: minio/minio:latest
    container_name: ${PROJECT_NAME}_minio
    restart: unless-stopped
    ports:
      - "9000:9000"     # S3 API
      - "9001:9001"     # Console
    volumes:
      - ./${PROJECT_NAME}.Deployment/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

networks:
  docker-network:
    driver: bridge